import Vue from 'vue'

import { PullRefresh, List, Icon, Tab, Tabs, Popup, DatetimePicker, Uploader, Cell, CellGroup, GridItem, Grid, Image as VanImage, Button, Tabbar, TabbarItem, Form, Field, NavBar, Toast, Dialog } from 'vant'
Vue.use(PullRefresh)
Vue.use(Icon)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Popup)
Vue.use(DatetimePicker)
Vue.use(Uploader)
Vue.use(CellGroup)
Vue.use(Dialog)
Vue.use(Cell)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(VanImage)
Vue.use(Button)
Vue.use(Form)
Vue.use(Toast)
Vue.use(Field)
Vue.use(List)
